version: 1.1.{build}
build_script:
- cmd: >-
    pip install pyinstaller pillow

    pyinstaller --onefile main.py --i=icon/dataprison.png

    git config user.email "avdorr12345@gmail.com"

    git config user.name "Abdulmumin1"

    git add dist/main.exe

    git commit -m "added exe file"

    git push origin modified
on_success:
  - git config --global user.email "Your email"
  - git config --global user.name "Your Name"
  - git commit -am"win.exe"
  - git push https://github.com/Abdulmumin1/packages modified
